export const types ={
    SUMMARIZE: "SUMMARIZE",
    DIFFERENCE:"DIFFERENCE",
    MULTIPLIES:"MULTIPLIES",
    DIVISION:"DIVISION",
    GET_FIRST_INPUT: "GET_FIRST_INPUT",
    GET_SECOND_INPUT: "GET_SECOND_INPUT",
}
